### PR TITLE
penasa_wiki19

### PR DESCRIPTION
**Pull request by valepenasa**

### CODE REVIEW

**Comment by minimalparts** [comment]
Hi @valepenasa, you have pushed the wrong file. It should be 

wiki[your-file-number]_top_50_categories_freqs.txt 

Could you please amend? Thanks very much :)

**Comment by valepenasa** [comment]
I added the freqs file, hope it is the right one.

**Comment by valepenasa** [comment]
Dear Prof,
sorry for the mistake. I upload the right one now, I hope. I am currently trying to find out how GitHub works (this is the first time I use it) and I am not sure I made an effective change in my pull request. Tell me if you can see the file and if it is the right one :)

**Comment by minimalparts** [comment]
This is great, thanks! And yes, GitHub can be tricky :) But it's a good skill to learn in the long term!
Thanks again for the file.

**Pull request merged**
